/**
 * Google Gemini Image Generation Provider
 * Uses Gemini API with image generation capabilities
 */

const logger = require('../../utils/logger');

async function generate(options) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('GEMINI_API_KEY not configured');

  const model = process.env.GEMINI_MODEL || 'gemini-2.0-flash-preview-image-generation';

  logger.info(`[Gemini] Generating image with model=${model}`);

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [{
        parts: [{
          text: `Generate an image: ${options.prompt}`,
        }],
      }],
      generationConfig: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    logger.error(`[Gemini] API error ${response.status}: ${errorText}`);

    if (response.status === 400 || response.status === 403) {
      throw new Error('Invalid Gemini API key or model access denied. Please check your GEMINI_API_KEY.');
    }
    if (response.status === 429) {
      throw new Error('Gemini rate limit exceeded. Please wait a moment and try again.');
    }
    throw new Error(`Gemini API error (${response.status}): ${errorText.substring(0, 200)}`);
  }

  const data = await response.json();

  // Extract image from response
  const candidates = data.candidates || [];
  let imageData = null;
  let textResponse = '';

  for (const candidate of candidates) {
    const parts = candidate.content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        imageData = part.inlineData;
      }
      if (part.text) {
        textResponse += part.text;
      }
    }
  }

  if (!imageData) {
    throw new Error('No image was generated by Gemini. The model may not support image generation or the prompt was filtered.');
  }

  // Convert base64 to data URL
  const mimeType = imageData.mimeType || 'image/png';
  const imageUrl = `data:${mimeType};base64,${imageData.data}`;

  return {
    url: imageUrl,
    prompt: options.prompt,
    revisedPrompt: textResponse || null,
  };
}

module.exports = { generate };